SchoolStation/SchoolStation/urls.py
from django.contrib import admin
from django.urls import include, path

from main.views import index,docs,info

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('docs/', docs, name='docs'),
    path('info/', info, name='info'),
    path('users/', include('users.urls', namespace='users'))

]

SchoolStation/urls.py
from django.contrib import admin
from django.urls import include, path

from main.views import index,docs,info

from api.views import ( DATTAPIVIEVSET, CheckUserExists, RegisterUser,
                        UpdateTelegramIDView, UpdateAddrView, GetUserProfile,
                        GetSensorData, GetPastSensorData)

from rest_framework import routers

router = routers.SimpleRouter()
router.register(r'sensors', DATTAPIVIEVSET)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('docs/', docs, name='docs'),
    path('info/', info, name='info'),
    path('users/', include('users.urls', namespace='users')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/', include(router.urls)),
    path('api/v1/check-user/', CheckUserExists.as_view(), name='check_user_exists'),
    path('api/v1/register/', RegisterUser.as_view(), name='register_user'),
    path('api/v1/update-telegram-id/', UpdateTelegramIDView.as_view(), name='update_telegram_id'),
    path('api/v1/update-addr/', UpdateAddrView.as_view(), name='update_addr'),
    path('api/v1/profile/', GetUserProfile.as_view(), name='get_profile'),
    path('api/v1/sensor/latest/', GetSensorData.as_view(), name='get_latest_sensor_data'),
    path('api/v1/sensor/history/', GetPastSensorData.as_view(), name='get_sensor_history'),
]

users/urls.py
from django.urls import path
from users.views import login, registrarion, logout

app_name = 'users'

urlpatterns = [
    path('login/', login, name = 'login'),
    path('registration/', registrarion, name = 'registration'),
    path('logout/', logout, name='logout')
]

SchoolStation/main/models.py
from django.db import models

# Create your models here.
class DATT(models.Model):
    room = models.IntegerField(unique=True)
    CO = models.CharField(max_length=8)
    HUM = models.CharField(max_length=3)
    TEMP = models.CharField(max_length=4)
    time = models.TimeField(auto_now=True)

main/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import transaction
from django.db.models import Max

# Create your models here.
class DATT(models.Model):
    secure = models.IntegerField(default=0)
    addr = models.IntegerField()
    room = models.IntegerField()
    CO = models.CharField(max_length=8)
    HUM = models.CharField(max_length=8)
    TEMP = models.CharField(max_length=8)
    time = models.TimeField(auto_now=True)

@receiver(post_save, sender=DATT)
def clean_old_records(sender, instance, created, **kwargs):
    if created:
        # Получаем 11-ю запись по времени (если существует)
        to_delete = DATT.objects.filter(
            addr=instance.addr,
            room=instance.room
        ).order_by('-id').values_list('id', flat=True)[10:]
        
        if to_delete.exists():
            with transaction.atomic():
                DATT.objects.filter(id__in=list(to_delete)).delete()

main/forms.py
from django import forms

class sencorIDform(forms.Form):
    sensor_id = forms.IntegerField()

SchoolStation/main/views.py
from django.shortcuts import render
from .models import DATT


def index(request):
    context = {
        'title': 'School'
    }
    return render(request, 'main\index.html',context=context)

def docs(request):
    return render(request, 'main\docks.html')

def info(request):
    context = {
        'dat':DATT.objects.all(),
    }
    return render(request, 'main\info.html', context)

main/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.db.models import Max, Subquery, OuterRef
from .models import DATT
from .forms import sencorIDform


def index(request):
    context = {
        'title': 'School'
    }
    return render(request, 'main/index.html',context=context)

def docs(request):
    return render(request, 'main/docks.html')

@login_required
def info(request):
    user = request.user
    latest_ids = DATT.objects.values('addr', 'room').annotate(
        latest_id=Max('id')
    ).values_list('latest_id', flat=True)
    
    # Получаем полные объекты для этих ID
    sensors = DATT.objects.filter(id__in=latest_ids).order_by('-id')
    if request.method == "POST":
        form = sencorIDform(request.POST)
        sensor_id = request.POST['sensor_id']
        profile = user.userprofile
        profile.sensor_id = sensor_id 
    else:
        form = sencorIDform()
    if user.username == 'root':
        context = {
        'dat':sensors,
        'form': form,
        }
        return render(request, 'main/info.html', context)
    else:
        try:
            profile = user.userprofile 
            sensor_id = profile.sensor_id
            print(sensor_id)
            context = {
            'dat':sensors.filter(addr=sensor_id),
            'form': form,
            }
            return render(request, 'main/info.html', context)
        except: 
            return render(request, 'main/index.html', context)
    

main/templates/main/docks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/styles/index-data/index-main.css">
    <link rel="stylesheet" href="/static/styles/index-data/nav.css">
    <link rel="stylesheet" href="/static/styles/docks/docks.css">
    <link rel="stylesheet" href="/static/styles/index-data/footer.css">
</head>
<body>
    <section class="docks">
        <div class="container">
            <nav class="navigation">
                <div class="navigation-logo">
                    <img class="navigation-logo__img" src="static/data/img/photo_2025-02-14_16-50-33.png" alt="ERROR"  width="200px">
                    <div class="navigation-logo__info">
                        <h3 class="navigation-logo__title">Школьная Wifi станция</h3>
                        <p class="navigation-logo__paragraph">Мы за безопасность и удобство!</p>
                    </div>
                </div>
                <div class="navigation-links">
                    <a href="{% url 'index' %}"><button class="navigation-links__item">Главная</button></a>
                    {% if user.is_authenticated %}
                        <a href="{% url 'info' %}"><button class="navigation-links__item ">Показания</button></a>
                        <a href="{% url 'users:logout' %}"><button class="navigation-links__item ">Выйти</button></a>
                    {% endif %}
                    <a href="{% url 'docs' %}"><button class="navigation-links__item navigation-links__item-active">Документация</button></a>
                    {% if not user.is_authenticated %}
                        <a href="{% url 'users:login' %}"><button class="navigation-links__item">Вход</button></a>
                        <a href="{% url 'users:registration' %}"><button class="navigation-links__item">Регистрация</button></a>
                    {% endif %}
                </div>
            </nav>
            <div class="docks-content">
                


            </div>
        </div>
    </section>
    <footer class="footer footer-fixed">
        <div class="footer-content">
            <h4 class="footer-content__title">Информация о проекте и разработчике: </h4>
            <div class="footer-content__data">
                <img class="footer-content__data-img" src="/static/data/img/git-logo.png" alt="ERROR">
                <a href="https://github.com/zeniafiat"><button class="navigation-links__item">Наш github</button></a>
                <a href="eugeniydevtalent@gmail.com"><button class="navigation-links__item">Написать по вопросам</button></a>
            </div>
        </div>
    </footer>
</body>
</html>

main/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/styles/index-data/index-main.css">
    <link rel="stylesheet" href="/static/styles/index-data/nav.css">
    <link rel="stylesheet" href="/static/styles/preview/preview.css">
    <link rel="stylesheet" href="/static/styles/index-data/footer.css">
    <title>{{title}}</title>
</head>
<body>
    <section class="preview">
        <div class="container">
            <nav class="navigation">
                <div class="navigation-logo">
                    <img class="navigation-logo__img" src="/static/data/img/photo_2025-02-14_16-50-33.png" alt="ERROR"  width="200px">
                    <div class="navigation-logo__info">
                        <h3 class="navigation-logo__title">Школьная Wifi станция</h3>
                        <p class="navigation-logo__paragraph">Мы за безопасность и удобство!</p>
                    </div>
                </div>
                <div class="navigation-links">
                    <a href="{% url 'index' %}"><button class="navigation-links__item navigation-links__item-active">Главная</button></a>
                    {% if user.is_authenticated %}
                        <a href="{% url 'info' %}"><button class="navigation-links__item ">Показания</button></a>
                        <a href="{% url 'users:logout' %}"><button class="navigation-links__item ">Выйти</button></a>
                    {% endif %}
                    <a href="{% url 'docs' %}"><button class="navigation-links__item">Документация</button></a>
                    {% if not user.is_authenticated %}
                        <a href="{% url 'users:login' %}"><button class="navigation-links__item">Вход</button></a>
                        <a href="{% url 'users:registration' %}"><button class="navigation-links__item">Регистрация</button></a>
                    {% endif %}
                </div>
            </nav>
            <div class="preview-content">
                <div class="preview-content__info">
                    <h2 class="preview-content__info-title">О проекте</h2>
                    <p class="preview-content__info-paragraph">Проект «Wifi-School-Station» представляет собой систему мониторинга окружающей среды и обеспечения безопасности помещений, для школы, которая собирает данные с датчиков и передает их на сервер для дальнейшей обработки и хранения. Пользователь может запросить актуальные данные или историю показателей через Telegram-бота. Проект разработан на базе микроконтроллера LOLIN(WEMOS) D1 с использованием OLED-дисплея, датчиков MQ-5, DHT-22, HC-SR505 и RFID-RC522. Программная часть включает в себя код для микроконтроллера, написанный на C++ в Arduino IDE, и серверную часть, реализованную с использованием Python, SQLite и библиотеки aiogram для Telegram-бота.</p>
                    <p class="preview-content__info-paragraph">Проект может быть использован для мониторинга окружающей среды в учебных заведениях, офисах, домах или других помещениях а также обеспечения безопастности. Основные функции:

                        Отображение данных: Текущие показания датчиков отображаются на OLED-дисплее.
                        Передача данных: Данные передаются на сервер для хранения и обработки.
                        Запрос данных через Telegram-бота: Пользователь может запросить актуальные данные или историю показаний через Telegram-бота.</p>
                    <a href="https://github.com/zeniafiat/Wifi-School-Station"><button class="preview-content__info-button navigation-links__item">Ссылка на проект</button></a>
                </div>
                <img src="/static/data/img/dat.png" alt="ERROR" height="500px" width="700px">
            </div>
        </div>
    </section>
    <footer class="footer footer-fixed">
        <div class="footer-content">
            <h4 class="footer-content__title">Информация о проекте и разработчике: </h4>
            <div class="footer-content__data">
                <img class="footer-content__data-img" src="/static/data/img/git-logo.png" alt="ERROR">
                <a href="https://github.com/zeniafiat"><button class="navigation-links__item">Наш github</button></a>
                <a href="eugeniydevtalent@gmail.com"><button class="navigation-links__item">Написать по вопросам</button></a>
            </div>
        </div>
    </footer>
</body>
</html>

main/templates/main/info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/styles/index-data/index-main.css">
    <link rel="stylesheet" href="/static/styles/index-data/nav.css">
    <link rel="stylesheet" href="/static/styles/info/info.css">
    <link rel="stylesheet" href="/static/styles/index-data/footer.css">
    <link rel="stylesheet" href="/static/styles/login/login.css">
</head>
<body>
    <section class="information">
        <div class="container">
            <nav class="navigation">
                <div class="navigation-logo">
                    <img class="navigation-logo__img" src="/static/data/img/photo_2025-02-14_16-50-33.png" alt="ERROR"  width="200px">
                    <div class="navigation-logo__info">
                        <h3 class="navigation-logo__title">Школьная Wifi станция</h3>
                        <p class="navigation-logo__paragraph">Мы за безопасность и удобство!</p>
                    </div>
                </div>
                <div class="navigation-links">
                    <a href="{% url 'index' %}"><button class="navigation-links__item">Главная</button></a>
                    {% if user.is_authenticated %}
                        <a href="{% url 'info' %}"><button class="navigation-links__item navigation-links__item-active">Показания</button></a>
                        <a href="{% url 'users:logout' %}"><button class="navigation-links__item ">Выйти</button></a>
                    {% endif %}
                    <a href="{% url 'docs' %}"><button class="navigation-links__item">Документация</button></a>
                    {% if not user.is_authenticated %}
                        <a href="{% url 'users:login' %}"><button class="navigation-links__item">Вход</button></a>
                        <a href="{% url 'users:registration' %}"><button class="navigation-links__item">Регистрация</button></a>
                    {% endif %}
                </div>
            </nav>
            {% if user.username != 'root' %}
                <div class="login-container" style="margin: 20px auto">
                        <form action="{% url 'info' %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="{{form.username.id_for_lable}}">Sensor ID</label>
                                {{form.sensor_id}}
                            </div>
                            <button type="submit" class="login-btn">Submit</button>
                        </form>
                </div>
            {% endif %}
            <div class="information-cards">
                {%for data in dat%}
                <div class="information-cards__item">
                    {% if data.secure != 0 %}
                        <h3 class="information-cards__item-title" style="color: red;">ОПАСНОСТЬ</h3>
                    {% endif%}
                    <h3 class="information-cards__item-title">{{data.room}} Кабинет</h3>
                    <img class="navigation-logo__img information-cards__item-img" src="/static/data/img/photo_2025-02-14_16-50-33.png" alt="ERROR"  width="200px">
                    <p class="information-cards__item-paragraph">Угарный газ: {{data.CO}}</p>
                    <p class="information-cards__item-paragraph">Влажность: {{data.HUM}}</p>
                    <p class="information-cards__item-paragraph">Температура: {{data.TEMP}}</p>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <footer class="footer footer-fixed">
        <div class="footer-content">
            <h4 class="footer-content__title">Информация о проекте и разработчике: </h4>
            <div class="footer-content__data">
                <img class="footer-content__data-img" src="/static/data/img/git-logo.png" alt="ERROR">
                <a href="https://github.com/zeniafiat"><button class="navigation-links__item">Наш github</button></a>
                <a href="eugeniydevtalent@gmail.com"><button class="navigation-links__item">Написать по вопросам</button></a>
            </div>
        </div>
    </footer>
</body>
</html>